<script setup>
import { computed } from 'vue';
import { Refresh, Aim, Cpu, Coin, Clock, TrendCharts } from '@element-plus/icons-vue';
import PageHeader from '../components/common/PageHeader.vue';
import EChart from '../components/charts/EChart.vue';
import { platformStore } from '../stores/platform.js';
const trendOption=computed(()=>({backgroundColor:'transparent',tooltip:{trigger:'axis'},legend:{top:5,textStyle:{color:'#8fa4bf'}},grid:{left:45,right:25,top:48,bottom:35},xAxis:{type:'category',boundaryGap:false,data:['07-11','07-12','07-13','07-14','07-15','07-16','07-17'],axisLabel:{color:'#70849e'},axisLine:{lineStyle:{color:'rgba(148,181,226,.18)'}}},yAxis:{type:'value',splitLine:{lineStyle:{color:'rgba(148,181,226,.08)'}},axisLabel:{color:'#70849e'}},series:[{name:'检测任务',type:'line',smooth:true,showSymbol:false,data:[286,341,398,362,455,512,568],lineStyle:{width:3},areaStyle:{opacity:.08}},{name:'车辆目标',type:'line',smooth:true,showSymbol:false,data:[1200,1560,1810,1690,2240,2610,2940],lineStyle:{width:2}}]}));
const classOption={backgroundColor:'transparent',tooltip:{trigger:'item'},legend:{bottom:4,textStyle:{color:'#8fa4bf'}},series:[{type:'pie',radius:['45%','70%'],center:['50%','45%'],label:{color:'#a8bad0'},data:[{name:'轿车',value:54},{name:'货车',value:21},{name:'公交车',value:12},{name:'摩托车',value:8},{name:'行人',value:5}]}]};
</script>
<template>
  <div class="page-stack vue-page">
    <PageHeader title="数据看板" description="汇总检测任务、训练状态、数据集资产、系统健康度与近期业务趋势。"><button class="btn btn-ghost"><el-icon><Refresh/></el-icon>刷新数据</button><router-link custom to="/app/detection" v-slot="{navigate}"><button class="btn btn-primary" @click="navigate"><el-icon><Aim/></el-icon>新建检测</button></router-link></PageHeader>
    <div class="data-card-grid"><article class="panel metric-mini"><span>今日检测任务</span><strong>568</strong><small>较昨日 +10.9%</small></article><article class="panel metric-mini"><span>识别车辆目标</span><strong>2,940</strong><small>平均 5.18 个/任务</small></article><article class="panel metric-mini"><span>训练中任务</span><strong>{{platformStore.tasks.filter(t=>t.status==='running').length}}</strong><small>GPU 利用率 68%</small></article><article class="panel metric-mini"><span>数据集图像</span><strong>{{platformStore.datasets.reduce((s,d)=>s+d.images,0).toLocaleString()}}</strong><small>{{platformStore.datasets.length}} 个数据集</small></article></div>
    <div class="page-two-col"><section class="panel"><div class="panel-title"><div><strong>近 7 日业务趋势</strong><span>检测任务与车辆识别量</span></div><span class="status-badge status-running"><i></i>实时数据</span></div><EChart :option="trendOption" height="330px"/></section><section class="panel"><div class="panel-title"><div><strong>车辆类别构成</strong><span>本日识别结果</span></div></div><EChart :option="classOption" height="330px"/></section></div>
    <div class="page-two-col"><section class="panel"><div class="panel-title"><div><strong>训练任务概况</strong><span>最新四个模型任务</span></div><router-link to="/app/training" class="text-link">查看全部</router-link></div><table class="page-table"><thead><tr><th>任务</th><th>模型</th><th>进度</th><th>mAP50</th></tr></thead><tbody><tr v-for="task in platformStore.tasks" :key="task.id"><td><strong>{{task.name}}</strong><br><small>{{task.dataset}}</small></td><td>{{task.model}}</td><td>{{task.progress}}%</td><td>{{task.map50.toFixed(3)}}</td></tr></tbody></table></section><section class="panel"><div class="panel-title"><div><strong>系统运行状态</strong><span>核心服务延迟</span></div><router-link to="/app/monitoring" class="text-link">系统监控</router-link></div><div style="padding:12px 20px"><div v-for="service in platformStore.services" :key="service.key" class="context-row"><span><i class="health-dot" style="display:inline-block;margin-right:8px"></i>{{service.name}}</span><strong>{{service.latency}} ms</strong></div></div></section></div>
  </div>
</template>
