<script setup>
import { computed, ref } from 'vue';
import { VideoPlay, Download, Upload, Check, TrendCharts } from '@element-plus/icons-vue';
import { ElMessage } from 'element-plus';
import PageHeader from '../components/common/PageHeader.vue';
import EChart from '../components/charts/EChart.vue';
import { platformStore } from '../stores/platform.js';
const taskId=ref(101);const running=ref(false);const report=ref({precision:.89,recall:.864,map50:.909,map5095:.641,speed:10.6});
const task=computed(()=>platformStore.tasks.find(t=>t.id===taskId.value)||platformStore.tasks[0]);
const prOption=computed(()=>({backgroundColor:'transparent',tooltip:{trigger:'axis'},legend:{top:4,textStyle:{color:'#8fa4bf'}},grid:{left:46,right:24,top:45,bottom:35},xAxis:{type:'value',min:0,max:1,name:'Recall',axisLabel:{color:'#70849e'},splitLine:{lineStyle:{color:'rgba(148,181,226,.08)'}}},yAxis:{type:'value',min:0,max:1,name:'Precision',axisLabel:{color:'#70849e'},splitLine:{lineStyle:{color:'rgba(148,181,226,.08)'}}},series:[{name:'Vehicle',type:'line',smooth:true,showSymbol:false,data:Array.from({length:30},(_,i)=>[i/29,Math.max(.05,1-Math.pow(i/29,2.6)*.75)]),lineStyle:{width:3},areaStyle:{opacity:.05}},{name:'Truck',type:'line',smooth:true,showSymbol:false,data:Array.from({length:30},(_,i)=>[i/29,Math.max(.04,.97-Math.pow(i/29,2.1)*.8)]),lineStyle:{width:2}}]}));
async function evaluate(){running.value=true;await new Promise(r=>setTimeout(r,900));running.value=false;ElMessage.success('验证完成，评估报告已更新')}
</script>
<template>
  <div class="page-stack vue-page">
    <PageHeader title="模型评估" description="对训练模型执行验证集评估，输出 Precision、Recall、mAP、混淆矩阵和推理性能报告。"><select v-model.number="taskId" class="header-select"><option v-for="item in platformStore.tasks" :key="item.id" :value="item.id">{{item.name}}</option></select><button class="btn btn-primary" :disabled="running" @click="evaluate"><span v-if="running" class="spinner"></span><el-icon v-else><VideoPlay/></el-icon>{{running?'正在评估…':'运行评估'}}</button></PageHeader>
    <div class="data-card-grid"><article class="panel metric-mini"><span>Precision</span><strong>{{(report.precision*100).toFixed(1)}}%</strong><small>精确率</small></article><article class="panel metric-mini"><span>Recall</span><strong>{{(report.recall*100).toFixed(1)}}%</strong><small>召回率</small></article><article class="panel metric-mini"><span>mAP@0.5</span><strong>{{(report.map50*100).toFixed(1)}}%</strong><small>核心指标</small></article><article class="panel metric-mini"><span>推理耗时</span><strong>{{report.speed}} ms</strong><small>单张 640px</small></article></div>
    <div class="page-two-col"><section class="panel"><div class="panel-title"><div><strong>Precision–Recall 曲线</strong><span>{{task.name}} · ECharts</span></div><button class="btn btn-ghost btn-sm"><el-icon><Download/></el-icon>导出图表</button></div><EChart :option="prOption" height="350px"/></section><section class="panel"><div class="panel-title"><div><strong>评估结论</strong><span>Validation Summary</span></div><span class="status-badge status-success"><i></i>通过</span></div><div style="padding:20px"><div class="validation-result success"><el-icon><Check/></el-icon><div><strong>模型满足部署要求</strong><p>车辆类别整体表现稳定，mAP@0.5 达到 90.9%。建议继续补充夜间货车与遮挡场景。</p></div></div><div class="context-row"><span>评估数据集</span><strong>{{task.dataset}}</strong></div><div class="context-row"><span>模型版本</span><strong>{{task.model}}</strong></div><div class="context-row"><span>mAP50-95</span><strong>{{report.map5095.toFixed(3)}}</strong></div><div class="context-row"><span>部署建议</span><strong>ONNX / TensorRT</strong></div><div class="action-row" style="margin-top:18px"><button class="btn btn-primary"><el-icon><Download/></el-icon>导出报告</button><button class="btn btn-ghost"><el-icon><Upload/></el-icon>测试图片</button></div></div></section></div>
    <section class="panel"><div class="panel-title"><div><strong>类别混淆矩阵</strong><span>真实类别与预测类别分布</span></div></div><div class="confusion-wrap" style="padding:20px"><div class="confusion-matrix"><div></div><strong>Car</strong><strong>Truck</strong><strong>Bus</strong><strong>Person</strong><template v-for="(row,r) in [[92,4,2,2],[6,86,5,3],[2,5,90,3],[1,2,3,94]]" :key="r"><strong>{{['Car','Truck','Bus','Person'][r]}}</strong><span v-for="(value,c) in row" :key="c" :style="{opacity:.35+value/140}">{{value}}</span></template></div></div></section>
  </div>
</template>
