"""init: create users, detection_records, training_tasks tables

Revision ID: c553a1f550a3
Revises: 
Create Date: 2026-07-07 14:19:00.790410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c553a1f550a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Permission code, such as detection:task:create'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Permission name'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='Module: auth/detection/training/agent/system'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Permission description'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Role code, such as admin/operator/viewer'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='Role display name'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Role description'),
    sa.Column('is_system', sa.Boolean(), nullable=True, comment='Whether this is a built-in role'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Created time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Username'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Hashed password'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Phone number'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='Avatar URL'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether the user is active'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='Whether the user is a superuser'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='Last login time'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Created time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Updated time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Owner user'),
    sa.Column('session_uuid', sa.String(length=100), nullable=False, comment='Session UUID'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='Session title'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Status: active/archived'),
    sa.Column('message_count', sa.Integer(), nullable=True, comment='Message count'),
    sa.Column('last_message_at', sa.DateTime(), nullable=True, comment='Last message time'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Created time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_session_uuid'), 'chat_sessions', ['session_uuid'], unique=True)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('detection_scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Scene code, such as remote_sensing'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='Scene display name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Scene description'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Category: agriculture/industry/remote_sensing/medical/traffic'),
    sa.Column('class_names', sa.JSON(), nullable=False, comment='Class list'),
    sa.Column('class_names_cn', sa.JSON(), nullable=True, comment='Chinese class name mapping'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether the scene is active'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='Creator user id'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Operating user'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='Redundant username for queries'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='Module: auth/detection/training/agent/system'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Action: create/update/delete/login/export'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='Target type: user/task/model/session'),
    sa.Column('target_id', sa.String(length=100), nullable=True, comment='Target id'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Operation description'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='Client IP'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='Client User-Agent'),
    sa.Column('request_method', sa.String(length=10), nullable=True, comment='HTTP method'),
    sa.Column('request_path', sa.String(length=500), nullable=True, comment='Request path'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Result: success/failure'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message on failure'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Created time'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_created_at'), 'operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_logs_user_id'), 'operation_logs', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Chat session'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Role: user/assistant/tool/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message content'),
    sa.Column('agent_used', sa.String(length=50), nullable=True, comment='Agent used: supervisor/detection/analysis/qa'),
    sa.Column('tool_calls', sa.JSON(), nullable=True, comment='Tool call records'),
    sa.Column('tool_result', sa.Text(), nullable=True, comment='Tool call result'),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='Token usage'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Latency in ms'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Created time'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('training_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Operating user'),
    sa.Column('scene_id', sa.Integer(), nullable=False, comment='Related scene'),
    sa.Column('task_uuid', sa.String(length=100), nullable=False, comment='Task UUID'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Status: pending/running/completed/failed/cancelled'),
    sa.Column('model_name', sa.String(length=50), nullable=True, comment='Base model'),
    sa.Column('epochs', sa.Integer(), nullable=True, comment='Training epochs'),
    sa.Column('img_size', sa.Integer(), nullable=True, comment='Image size'),
    sa.Column('batch_size', sa.Integer(), nullable=True, comment='Batch size'),
    sa.Column('device', sa.String(length=20), nullable=True, comment='Training device: 0/1/cpu'),
    sa.Column('optimizer', sa.String(length=20), nullable=True, comment='Optimizer: SGD/Adam/AdamW'),
    sa.Column('lr0', sa.Float(), nullable=True, comment='Initial learning rate'),
    sa.Column('augment_config', sa.JSON(), nullable=True, comment='Data augmentation config'),
    sa.Column('current_epoch', sa.Integer(), nullable=True, comment='Current epoch'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='Progress percentage from 0 to 100'),
    sa.Column('dataset_path', sa.String(length=500), nullable=True, comment='Dataset path'),
    sa.Column('dataset_size', sa.Integer(), nullable=True, comment='Number of dataset images'),
    sa.Column('data_yaml', sa.String(length=500), nullable=True, comment='data.yaml path'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message on failure'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Created time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Updated time'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='Training started time'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Training completed time'),
    sa.ForeignKeyConstraint(['scene_id'], ['detection_scenes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_tasks_scene_id'), 'training_tasks', ['scene_id'], unique=False)
    op.create_index(op.f('ix_training_tasks_task_uuid'), 'training_tasks', ['task_uuid'], unique=True)
    op.create_index(op.f('ix_training_tasks_user_id'), 'training_tasks', ['user_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False, comment='Related scene'),
    sa.Column('training_task_id', sa.Integer(), nullable=True, comment='Source training task'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='Version, such as v1.0.0'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='Model name'),
    sa.Column('model_type', sa.String(length=50), nullable=True, comment='Model type'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Status: active/archived/deleted'),
    sa.Column('model_path', sa.String(length=500), nullable=False, comment='Local model file path'),
    sa.Column('minio_url', sa.String(length=500), nullable=True, comment='MinIO URL'),
    sa.Column('map50', sa.Float(), nullable=True, comment='mAP@0.50'),
    sa.Column('map50_95', sa.Float(), nullable=True, comment='mAP@0.50:0.95'),
    sa.Column('precision', sa.Float(), nullable=True, comment='Precision'),
    sa.Column('recall', sa.Float(), nullable=True, comment='Recall'),
    sa.Column('per_class_ap', sa.JSON(), nullable=True, comment='Per-class AP'),
    sa.Column('description', sa.Text(), nullable=True, comment='Version description'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='Model file size in bytes'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='Whether this is the default model'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Created time'),
    sa.ForeignKeyConstraint(['scene_id'], ['detection_scenes.id'], ),
    sa.ForeignKeyConstraint(['training_task_id'], ['training_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_scene_id'), 'model_versions', ['scene_id'], unique=False)
    op.create_table('training_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='Training task'),
    sa.Column('epoch', sa.Integer(), nullable=False, comment='Current epoch'),
    sa.Column('box_loss', sa.Float(), nullable=True, comment='Box loss'),
    sa.Column('cls_loss', sa.Float(), nullable=True, comment='Classification loss'),
    sa.Column('dfl_loss', sa.Float(), nullable=True, comment='DFL loss'),
    sa.Column('precision', sa.Float(), nullable=True, comment='Precision'),
    sa.Column('recall', sa.Float(), nullable=True, comment='Recall'),
    sa.Column('map50', sa.Float(), nullable=True, comment='mAP@0.50'),
    sa.Column('map50_95', sa.Float(), nullable=True, comment='mAP@0.50:0.95'),
    sa.Column('lr', sa.Float(), nullable=True, comment='Learning rate'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['training_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_metrics_task_id'), 'training_metrics', ['task_id'], unique=False)
    op.create_table('detection_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Operating user'),
    sa.Column('scene_id', sa.Integer(), nullable=False, comment='Detection scene'),
    sa.Column('model_version_id', sa.Integer(), nullable=True, comment='Model version used'),
    sa.Column('task_type', sa.String(length=20), nullable=False, comment='Detection type: single/batch/folder/video/camera'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Status: pending/processing/completed/failed'),
    sa.Column('total_images', sa.Integer(), nullable=True, comment='Total processed images'),
    sa.Column('total_objects', sa.Integer(), nullable=True, comment='Total detected objects'),
    sa.Column('total_inference_time', sa.Float(), nullable=True, comment='Total inference time in ms'),
    sa.Column('conf_threshold', sa.Float(), nullable=True, comment='Confidence threshold'),
    sa.Column('iou_threshold', sa.Float(), nullable=True, comment='NMS IoU threshold'),
    sa.Column('image_size', sa.Integer(), nullable=True, comment='Inference image size'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message on failure'),
    sa.Column('analysis_report', sa.Text(), nullable=True, comment='Analysis report in Markdown'),
    sa.Column('analysis_suggestion', sa.Text(), nullable=True, comment='Professional suggestion'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='Risk level: low/medium/high/critical'),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True, comment='Analysis completed time'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Created time'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Completed time'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['detection_scenes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_tasks_created_at'), 'detection_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_detection_tasks_scene_id'), 'detection_tasks', ['scene_id'], unique=False)
    op.create_index(op.f('ix_detection_tasks_user_id'), 'detection_tasks', ['user_id'], unique=False)
    op.create_table('detection_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='Detection task'),
    sa.Column('image_path', sa.String(length=500), nullable=False, comment='Original image path'),
    sa.Column('annotated_image_url', sa.String(length=500), nullable=True, comment='Annotated image MinIO URL'),
    sa.Column('class_name', sa.String(length=50), nullable=False, comment='Class name'),
    sa.Column('class_name_cn', sa.String(length=50), nullable=True, comment='Chinese class name'),
    sa.Column('class_id', sa.Integer(), nullable=False, comment='Class id'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confidence score from 0 to 1'),
    sa.Column('bbox', sa.JSON(), nullable=False, comment='Bounding box [x1, y1, x2, y2]'),
    sa.Column('inference_time', sa.Float(), nullable=True, comment='Inference time in ms'),
    sa.Column('image_width', sa.Integer(), nullable=True, comment='Image width'),
    sa.Column('image_height', sa.Integer(), nullable=True, comment='Image height'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['detection_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_results_class_name'), 'detection_results', ['class_name'], unique=False)
    op.create_index(op.f('ix_detection_results_task_id'), 'detection_results', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_results_task_id'), table_name='detection_results')
    op.drop_index(op.f('ix_detection_results_class_name'), table_name='detection_results')
    op.drop_table('detection_results')
    op.drop_index(op.f('ix_detection_tasks_user_id'), table_name='detection_tasks')
    op.drop_index(op.f('ix_detection_tasks_scene_id'), table_name='detection_tasks')
    op.drop_index(op.f('ix_detection_tasks_created_at'), table_name='detection_tasks')
    op.drop_table('detection_tasks')
    op.drop_index(op.f('ix_training_metrics_task_id'), table_name='training_metrics')
    op.drop_table('training_metrics')
    op.drop_index(op.f('ix_model_versions_scene_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_training_tasks_user_id'), table_name='training_tasks')
    op.drop_index(op.f('ix_training_tasks_task_uuid'), table_name='training_tasks')
    op.drop_index(op.f('ix_training_tasks_scene_id'), table_name='training_tasks')
    op.drop_table('training_tasks')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_operation_logs_user_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_created_at'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_table('detection_scenes')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_session_uuid'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
